apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/refresh: 2025-08-31T14:03:58Z
  creationTimestamp: 2025-08-31T07:28:49Z
  finalizers:
    - kargo.akuity.io/finalizer
  generation: 7
  name: prod
  namespace: swampup-2025-evidence-demo
  resourceVersion: "222004"
  uid: 1330470d-11b4-4eca-8059-6b4b2b322318
spec:
  promotionTemplate:
    spec:
      steps:
        - as: clone
          config:
            checkout:
              - branch: feature/RTDEV-62079-kargo
                path: ./src
            repoURL: https://github.com/jfrog/evidence-integration
          continueOnError: false
          if: ""
          uses: git-clone
        - as: app_details
          config:
            outputs:
              - fromExpression: app_id
                name: app_id
              - fromExpression: app_ver
                name: app_ver
            path: ./src/kargo/release_version
          continueOnError: false
          if: ""
          uses: json-parse
        - as: builds_details
          config:
            headers:
              - name: Authorization
                value: Bearer ${{ secret('evidence-trial-jpd-token').JF_TOKEN }}
            method: GET
            outputs:
              - fromExpression: sources[0].build.name
                name: build1_name
              - fromExpression: sources[0].build.number
                name: build1_number
              - fromExpression: sources[1].build.name
                name: build2_name
              - fromExpression: sources[1].build.number
                name: build2_number
            url: https://evidencetrial.jfrog.io/apptrust/api/v1/applications/${{
              outputs.app_details.app_id }}/versions/${{
              outputs.app_details.app_ver }}/content?include=sources
          continueOnError: false
          if: ""
          uses: http
        - config:
            path: ./src/argocd/manifests/deployment-${{ outputs.build_details.build1_name
              }}.yaml
            updates:
              key: spec.template.spec.containers.image
              value: evidencetrial.jfrog.io/commons-dev-docker-local/${{
                outputs.build_details.build1_name }}:${{
                outputs.build_details.build1_number }}
          uses: yaml-update
        - config:
            path: ./src/argocd/manifests/deployment-${{ outputs.build_details.build2_name
              }}.yaml
            updates:
              key: spec.template.spec.containers.image
              value: evidencetrial.jfrog.io/commons-dev-docker-local/${{
                outputs.build_details.build2_name }}:${{
                outputs.build_details.build2_number }}
          uses: yaml-update
        - config:
            author:
              email: kargo@jfrog.com
              name: kargo
            message: Updated ArgoCD to ${{ outputs.build_details.build1_name }}:${{
              outputs.build_details.build1_number }} and ${{
              outputs.build_details.build2_name }}:${{
              outputs.build_details.build2_number }}
            path: ./src
          uses: git-commit
        - config:
            path: ./src
          uses: git-push
  requestedFreight:
    - origin:
        kind: Warehouse
        name: quotopia-release-ver-warehouse
      sources:
        direct: true
        stages: []
